//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdsFacade
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bird
    {
        public int ID { get; set; }
        public string BirdName { get; set; }
        public string TypeOfBird { get; set; }
        public string ScientificName { get; set; }
    }
}
